"""finished models and relations

Revision ID: 0dc620a19ecd
Revises: 352b0a0cc6b5
Create Date: 2021-10-07 15:03:36.806440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dc620a19ecd'
down_revision = '352b0a0cc6b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('my_workouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('workout_id', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workout_id'], ['workout_name.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('workout_name', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('workout_name', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workout_name', 'updated_at')
    op.drop_column('workout_name', 'created_at')
    op.drop_table('my_workouts')
    # ### end Alembic commands ###
