"""updated relational database

Revision ID: 33052d0b49ea
Revises: 35b0f0000908
Create Date: 2021-10-08 11:56:26.783042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33052d0b49ea'
down_revision = '35b0f0000908'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workouts', sa.Column('category_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'workouts', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workouts', type_='foreignkey')
    op.drop_column('workouts', 'category_id')
    # ### end Alembic commands ###
