"""added name column to Workout model

Revision ID: b2c006c3f860
Revises: 6cfa0419ad9a
Create Date: 2021-10-08 08:34:48.008258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2c006c3f860'
down_revision = '6cfa0419ad9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workouts', sa.Column('name', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workouts', 'name')
    # ### end Alembic commands ###
